<?php

$_lang['yandexmapslocator'] = 'YandexMapsLocator';
$_lang['yandexmapslocator_snippet_desc'] = 'Yandex Maps store locator with search, list, map, and geolocation.';
$_lang['area_yandexmapslocator_main'] = 'Main';
$_lang['area_yandexmapslocator_tvs'] = 'Template Variables';
$_lang['area_yandexmapslocator_api'] = 'REST API v1';

$_lang['setting_yandexmapslocator_api_key'] = 'Yandex Maps API key';
$_lang['setting_yandexmapslocator_api_key_desc'] = 'JavaScript and Geocoder API key from Yandex Developer Console.';
$_lang['setting_yandexmapslocator_default_zoom'] = 'Default map zoom';
$_lang['setting_yandexmapslocator_default_zoom_desc'] = 'Initial map zoom in the snippet (1–19).';
$_lang['setting_yandexmapslocator_default_latitude'] = 'Default latitude';
$_lang['setting_yandexmapslocator_default_latitude_desc'] = 'Map center when user coordinates are not set.';
$_lang['setting_yandexmapslocator_default_longitude'] = 'Default longitude';
$_lang['setting_yandexmapslocator_default_longitude_desc'] = 'Map center when user coordinates are not set.';
$_lang['setting_yandexmapslocator_cluster'] = 'Enable marker clustering';
$_lang['setting_yandexmapslocator_cluster_desc'] = 'Group nearby markers into clusters on the map.';
$_lang['setting_yandexmapslocator_default_radius'] = 'Default search radius (km)';
$_lang['setting_yandexmapslocator_default_radius_desc'] = 'Max distance from center when sortby=distance.';
$_lang['setting_yandexmapslocator_distance_unit'] = 'Distance unit';
$_lang['setting_yandexmapslocator_distance_unit_desc'] = 'km or m for distance_formatted in output.';

$_lang['setting_yandexmapslocator_tv_address'] = 'TV: address';
$_lang['setting_yandexmapslocator_tv_address_desc'] = 'Template variable name for the store address.';
$_lang['setting_yandexmapslocator_tv_latitude'] = 'TV: latitude';
$_lang['setting_yandexmapslocator_tv_latitude_desc'] = 'Template variable name for latitude (number or string).';
$_lang['setting_yandexmapslocator_tv_longitude'] = 'TV: longitude';
$_lang['setting_yandexmapslocator_tv_longitude_desc'] = 'Template variable name for longitude (number or string).';
$_lang['setting_yandexmapslocator_tv_phone'] = 'TV: phone';
$_lang['setting_yandexmapslocator_tv_phone_desc'] = 'Template variable name for the store phone.';
$_lang['setting_yandexmapslocator_tv_email'] = 'TV: email';
$_lang['setting_yandexmapslocator_tv_email_desc'] = 'Template variable name for the store email.';
$_lang['setting_yandexmapslocator_tv_working_hours'] = 'TV: working hours';
$_lang['setting_yandexmapslocator_tv_working_hours_desc'] = 'Template variable name for schedule JSON or text.';
$_lang['setting_yandexmapslocator_tv_category'] = 'TV: category';
$_lang['setting_yandexmapslocator_tv_category_desc'] = 'Template variable name for the category filter.';
$_lang['setting_yandexmapslocator_tv_balloon_image'] = 'TV: balloon image';
$_lang['setting_yandexmapslocator_tv_balloon_image_desc'] = 'Template variable name for the popup image URL/path.';
$_lang['setting_yandexmapslocator_tv_marker_icon'] = 'TV: marker icon';
$_lang['setting_yandexmapslocator_tv_marker_icon_desc'] = 'Template variable name for the custom map marker icon.';
$_lang['setting_yandexmapslocator_default_balloon_image'] = 'Default balloon image';
$_lang['setting_yandexmapslocator_default_balloon_image_desc'] = 'Fallback popup image when a store has no balloon TV value.';
$_lang['setting_yandexmapslocator_marker_icon_size'] = 'Marker icon size';
$_lang['setting_yandexmapslocator_marker_icon_size_desc'] = 'Custom marker icon width and height in px, comma-separated (e.g. 32,32).';
$_lang['setting_yandexmapslocator_default_context'] = 'Default context';
$_lang['setting_yandexmapslocator_default_context_desc'] = 'Fallback when the active MODX context is unavailable (usually web).';
$_lang['setting_yandexmapslocator_timezone'] = 'Store timezone';
$_lang['setting_yandexmapslocator_timezone_desc'] = 'IANA timezone for open-now badges and working_now. Working hours TV values are local wall-clock for the store network, not server UTC. Examples: Europe/Moscow, Asia/Omsk.';
$_lang['setting_yandexmapslocator_allowed_contexts'] = 'Allowed contexts';
$_lang['setting_yandexmapslocator_allowed_contexts_desc'] = 'Comma-separated context keys for search.php and REST. Empty = any existing context.';

$_lang['setting_yandexmapslocator_api_enabled'] = 'REST API enabled';
$_lang['setting_yandexmapslocator_api_enabled_desc'] = 'REST kill switch (Pro package api.php). When No, REST returns 503 and the on-page locator uses search.php instead.';
$_lang['setting_yandexmapslocator_api_max_limit'] = 'Max request limit';
$_lang['setting_yandexmapslocator_api_max_limit_desc'] = 'Upper cap for pagination limit (default 100).';
$_lang['setting_yandexmapslocator_api_max_offset'] = 'Max request offset';
$_lang['setting_yandexmapslocator_api_max_offset_desc'] = 'Upper cap for offset to mitigate DoS (default 10000).';
$_lang['setting_yandexmapslocator_api_max_parents'] = 'Max parent IDs';
$_lang['setting_yandexmapslocator_api_max_parents_desc'] = 'How many parent IDs may be passed in parents (comma-separated).';
$_lang['setting_yandexmapslocator_api_geocode_rate_limit'] = 'Rate limit: geocode (req/min)';
$_lang['setting_yandexmapslocator_api_geocode_rate_limit_desc'] = 'Per-IP per-minute limit for geocode and address search.';
$_lang['setting_yandexmapslocator_api_list_rate_limit'] = 'Rate limit: list (req/min)';
$_lang['setting_yandexmapslocator_api_list_rate_limit_desc'] = 'Per-IP per-minute limit for GET /locations and detail.';
$_lang['setting_yandexmapslocator_api_cors_origins'] = 'CORS allowed origins';
$_lang['setting_yandexmapslocator_api_cors_origins_desc'] = 'Comma-separated origins (https://example.com). Empty — no CORS headers.';
$_lang['setting_yandexmapslocator_api_token'] = 'API Bearer token';
$_lang['setting_yandexmapslocator_api_token_desc'] = 'When set, Authorization: Bearer is required. Not the Yandex Maps api_key.';
$_lang['setting_yandexmapslocator_api_resource_tvs'] = 'TV whitelist for include=tv';
$_lang['setting_yandexmapslocator_api_resource_tvs_desc'] = 'Comma-separated TV names allowed in the tv block.';
$_lang['setting_yandexmapslocator_api_allowed_parents'] = 'Allowed parents (scope)';
$_lang['setting_yandexmapslocator_api_allowed_parents_desc'] = 'Comma-separated container IDs. Empty — no scope restriction.';
$_lang['setting_yandexmapslocator_api_trust_proxy'] = 'Trust X-Forwarded-For';
$_lang['setting_yandexmapslocator_api_trust_proxy_desc'] = 'For rate limiting behind a reverse proxy: use X-Forwarded-For as client IP.';

$_lang['yandexmapslocator_address'] = 'Address';
$_lang['yandexmapslocator_address_placeholder'] = 'Enter address';
$_lang['yandexmapslocator_find'] = 'Find';
$_lang['yandexmapslocator_searching'] = 'Searching…';
$_lang['yandexmapslocator_locate_me'] = 'My location';
$_lang['yandexmapslocator_show_all'] = 'All locations';
$_lang['yandexmapslocator_list'] = 'List';
$_lang['yandexmapslocator_map'] = 'Map';
$_lang['yandexmapslocator_route'] = 'Get directions';
$_lang['yandexmapslocator_show_on_map'] = 'Show on map';
$_lang['yandexmapslocator_open_now'] = 'Open';
$_lang['yandexmapslocator_closed_now'] = 'Closed';
$_lang['yandexmapslocator_filter_open_now'] = 'Open now';
$_lang['yandexmapslocator_empty'] = 'No stores found.';
$_lang['yandexmapslocator_search_label'] = 'Store search';
$_lang['yandexmapslocator_stores_list'] = 'Store list';
$_lang['yandexmapslocator_view_toggle'] = 'View mode';

$_lang['yandexmapslocator_err_empty_address'] = 'Address is required.';
$_lang['yandexmapslocator_err_address_not_found'] = 'Address not found.';
$_lang['yandexmapslocator_err_geolocation_denied'] = 'Location access denied. Allow location in your browser settings.';
$_lang['yandexmapslocator_err_geolocation_unavailable'] = 'Unable to determine your location.';
$_lang['yandexmapslocator_err_geolocation_timeout'] = 'Location request timed out.';
$_lang['yandexmapslocator_err_geolocation_failed'] = 'Geolocation failed.';
$_lang['yandexmapslocator_err_geolocation_unsupported'] = 'Geolocation is not supported by this browser.';
$_lang['yandexmapslocator_err_rate_limit'] = 'Too many requests. Please try again in a minute.';
$_lang['yandexmapslocator_err_search_failed'] = 'Search failed.';
$_lang['yandexmapslocator_err_invalid_response'] = 'Invalid server response.';
$_lang['yandexmapslocator_err_pro_required'] = 'REST API requires YandexMapsLocator Pro.';
